Repository CadQuery/cadquery, pull requests merged in 2022-02, with the labels that each got.

#978 Python 3.10 support
  azure-pipelines.yml
Labels: infrastructure

#992 Remove the hdf dep
  conda/meta.yaml
Labels: infrastructure

#975 Additional constraints
  azure-pipelines.yml
  cadquery/assembly.py
  cadquery/occ_impl/solver.py
  doc/assy.rst
  tests/test_assembly.py
Labels: assembly

#980 Change conda related sections in the README and the docs
  README.md
  cadquery/assembly.py
  doc/installation.rst
  doc/quickstart.rst
Labels: docs

#1005 Sketch parray fix
  cadquery/sketch.py
  tests/test_sketch.py
Labels: sketching
